// Mocks generated by Mockito 5.4.6 from annotations
// in surabhi/test/unit/features/auth/presentation/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:surabhi/core/domain/entities/user_entity.dart' as _i7;
import 'package:surabhi/core/errors/failures.dart' as _i6;
import 'package:surabhi/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:surabhi/features/auth/domain/usecases/login_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i4.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> call(
    _i4.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.UserEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> login(
    _i4.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.UserEntity>(
                    this,
                    Invocation.method(#login, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
              _FakeEither_1<_i6.Failure, bool>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.UserEntity>(
                    this,
                    Invocation.method(#checkAuthStatus, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.UserEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> request2FA(String? method) =>
      (super.noSuchMethod(
            Invocation.method(#request2FA, [method]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#request2FA, [method]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> verifyOTP(
    String? otp,
    String? method,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [otp, method]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
              _FakeEither_1<_i6.Failure, bool>(
                this,
                Invocation.method(#verifyOTP, [otp, method]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
