// Mocks generated by Mockito 5.4.6 from annotations
// in surabhi/test/unit/features/auth/domain/usecases/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:surabhi/core/errors/failures.dart' as _i5;
import 'package:surabhi/features/auth/domain/entities/user_entity.dart' as _i6;
import 'package:surabhi/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:surabhi/features/auth/domain/usecases/login_usecase.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> login(
    _i7.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#login, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#checkAuthStatus, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> sendTwoFactorCode(
    String? email,
    String? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendTwoFactorCode, [email, provider]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#sendTwoFactorCode, [email, provider]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> verifyTwoFactorCode(
    String? email,
    String? provider,
    String? code,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyTwoFactorCode, [
              email,
              provider,
              code,
              rememberMe,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#verifyTwoFactorCode, [
                  email,
                  provider,
                  code,
                  rememberMe,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserEntity>(
                    this,
                    Invocation.method(#refreshToken, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserEntity>>);
}
